/* Sync the FINAL AUTHORITY game from its canonical home into public/.
 *
 * Canonical source:  ../free-skills/games/final-authority/index.html
 * Deployed artifact: public/play/final-authority/index.html
 *
 * The site embeds the game but does not own it. This keeps one editable copy
 * (in free-skills) and treats the file under public/ the way dist/ is treated:
 * generated, never hand-edited.
 *
 * Netlify builds this repo alone and will not have ../free-skills. That is
 * fine — the artifact is committed, so the deploy uses the last synced copy.
 * This is a developer convenience and a drift check, not a build step.
 *
 *   node scripts/sync-game.mjs           copy if the source is present
 *   node scripts/sync-game.mjs --check   exit 1 if they differ (for CI)
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, "../../free-skills/games/final-authority/index.html");
const TARGET = resolve(here, "../public/play/final-authority/index.html");

const HEADER = `<!--
  DEPLOYED ARTIFACT — DO NOT EDIT THIS FILE.

  Canonical source: MenokoOG/free-skills -> games/final-authority/index.html
  Synced here by \`npm run sync:game\`, which copies from ../free-skills.

  This is a deployment copy in the same sense dist/ is a deployment copy. Edit
  the source in free-skills and re-run the sync. Editing here creates a second
  editable copy, which is exactly what "consume, don't fork" forbids.
-->
`;

const check = process.argv.includes("--check");

if (!existsSync(SOURCE)) {
  console.log(`sync:game - source not found at ${SOURCE}`);
  console.log("Clone MenokoOG/free-skills beside this repo to sync. Skipping.");
  process.exit(0);
}

const source = await readFile(SOURCE, "utf8");
const wanted = HEADER + "\r\n" + source;
const current = existsSync(TARGET) ? await readFile(TARGET, "utf8") : null;

if (current === wanted) {
  console.log("sync:game - already in sync.");
  process.exit(0);
}

if (check) {
  console.error("sync:game - DRIFT: public/play/final-authority/index.html differs from free-skills.");
  console.error("Run `npm run sync:game` and commit the result.");
  process.exit(1);
}

await mkdir(dirname(TARGET), { recursive: true });
await writeFile(TARGET, wanted, "utf8");
console.log(`sync:game - updated ${TARGET} (${wanted.length} bytes).`);
